export type ThemePaletteId =
  | "copper-wave"
  | "electric-slate"
  | "sage-mist"
  | "emerald-frost"
  | "retro-muted"
  | "peach-blossom"
  | "neon-flare"
  | "desert-cyan"
  | "blue-lagoon"
  | "cyber-citrus"
  | "golden-hour"
  | "midnight-berry"
  | "blush-mint"
  | "arctic-breeze"
  | "terracotta-sunset"
  | "olive-forest"
  | "autumn-spices"
  | "warm-clay"
  | "pine-ember"
  | "bio-lime";

export type PaletteDefinition = {
  id: ThemePaletteId;
  name: string;
  vibe: string;
  colors: [string, string, string, string, string];
  componentRoles: {
    sidebar: string;
    navbar: string;
    taskMenu: string;
    cards: string;
    accents: string;
  };
  light: Record<string, string>;
  dark: Record<string, string>;
};

/**
 * Calculates relative luminance for WCAG contrast checking.
 */
function getLuminance(hex: string): number {
  const cleanHex = hex.replace("#", "");
  const r = parseInt(cleanHex.substring(0, 2), 16) / 255;
  const g = parseInt(cleanHex.substring(2, 4), 16) / 255;
  const b = parseInt(cleanHex.substring(4, 6), 16) / 255;
  const a = [r, g, b].map((v) => (v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4)));
  return 0.2126 * a[0] + 0.7152 * a[1] + 0.0722 * a[2];
}

/**
 * Returns strictly White (#ffffff), Black (#000000), or Dark Grey (#1f2937 / #374151)
 * depending on the background luminance for optimal legibility.
 */
export function getOptimalTextColor(bgHex: string, type: "primary" | "muted" = "primary"): string {
  const lum = getLuminance(bgHex);
  // Dark background -> white or light text
  if (lum < 0.40) {
    return type === "muted" ? "#d1d5db" : "#ffffff";
  }
  // Light background -> black or dark grey text
  if (type === "muted") {
    return "#4b5563"; // Dark grey
  }
  return lum > 0.82 ? "#000000" : "#1f2937"; // Black or deep dark grey
}

export const PALETTES: PaletteDefinition[] = [
  {
    id: "copper-wave",
    name: "Copper Wave",
    vibe: "Deep teal and dark mahogany contrasted with vibrant coral-orange accents.",
    colors: ["#562C2C", "#F2542D", "#F5DFBB", "#0E9594", "#127475"],
    componentRoles: {
      sidebar: "Deep Mahogany (#562C2C)",
      navbar: "Dark Teal (#127475)",
      taskMenu: "Coral Orange (#F2542D)",
      cards: "Warm Sand (#F5DFBB)",
      accents: "Bright Teal (#0E9594)",
    },
    light: {
      "--palette-c1": "#562C2C",
      "--palette-c2": "#F2542D",
      "--palette-c3": "#F5DFBB",
      "--palette-c4": "#0E9594",
      "--palette-c5": "#127475",
      "--primary": "#127475",
      "--primary-foreground": "#ffffff",
      "--secondary": "#F5DFBB",
      "--secondary-foreground": "#1f2937",
      "--accent": "#F2542D",
      "--accent-foreground": "#ffffff",
      "--background": "#FAF6F0",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#F5DFBB",
      "--muted-foreground": "#4b5563",
      "--border": "#E5D4BE",
      "--input": "#E5D4BE",
      "--ring": "#127475",
      "--sidebar": "#562C2C",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#F2542D",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#6D3B3B",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#432121",
      "--sidebar-ring": "#F2542D",
      "--navbar": "#127475",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#0e5a5b",
      "--navbar-accent": "#0E9594",
      "--taskmenu": "#F2542D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#0E9594",
      "--teal": "#0E9594",
      "--teal-soft": "#E0F5F5",
      "--coral": "#F2542D",
      "--coral-soft": "#FDEAE5",
      "--gradient-brand": "linear-gradient(135deg, #F2542D 0%, #127475 100%)",
    },
    dark: {
      "--palette-c1": "#562C2C",
      "--palette-c2": "#F2542D",
      "--palette-c3": "#F5DFBB",
      "--palette-c4": "#0E9594",
      "--palette-c5": "#127475",
      "--primary": "#0E9594",
      "--primary-foreground": "#000000",
      "--secondary": "#3d2121",
      "--secondary-foreground": "#ffffff",
      "--accent": "#F2542D",
      "--accent-foreground": "#ffffff",
      "--background": "#140e0e",
      "--foreground": "#ffffff",
      "--card": "#1f1515",
      "--card-foreground": "#ffffff",
      "--popover": "#1f1515",
      "--popover-foreground": "#ffffff",
      "--muted": "#2d1c1c",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(245, 223, 187, 0.18)",
      "--input": "rgba(245, 223, 187, 0.22)",
      "--ring": "#0E9594",
      "--sidebar": "#2e1717",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#0E9594",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#452222",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(245, 223, 187, 0.14)",
      "--sidebar-ring": "#0E9594",
      "--navbar": "#0f4242",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(14, 149, 148, 0.3)",
      "--navbar-accent": "#127475",
      "--taskmenu": "#F2542D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#0E9594",
      "--teal": "#0E9594",
      "--teal-soft": "#1a3838",
      "--coral": "#F2542D",
      "--coral-soft": "#421d15",
      "--gradient-brand": "linear-gradient(135deg, #0E9594 0%, #F2542D 100%)",
    },
  },
  {
    id: "electric-slate",
    name: "Electric Slate",
    vibe: "Cool moody purple-slates highlighted by crisp cerulean blue.",
    colors: ["#272838", "#5D536B", "#7D6B91", "#989FCE", "#347FC4"],
    componentRoles: {
      sidebar: "Moody Slate (#272838)",
      navbar: "Purple Slate (#5D536B)",
      taskMenu: "Cerulean Blue (#347FC4)",
      cards: "Lavender Slate (#989FCE)",
      accents: "Slate Purple (#7D6B91)",
    },
    light: {
      "--palette-c1": "#272838",
      "--palette-c2": "#5D536B",
      "--palette-c3": "#7D6B91",
      "--palette-c4": "#989FCE",
      "--palette-c5": "#347FC4",
      "--primary": "#347FC4",
      "--primary-foreground": "#ffffff",
      "--secondary": "#EAEBF7",
      "--secondary-foreground": "#1f2937",
      "--accent": "#7D6B91",
      "--accent-foreground": "#ffffff",
      "--background": "#F4F5FB",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E5E6F5",
      "--muted-foreground": "#4b5563",
      "--border": "#D2D4E8",
      "--input": "#D2D4E8",
      "--ring": "#347FC4",
      "--sidebar": "#272838",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#347FC4",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#3B3D55",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#1A1B27",
      "--sidebar-ring": "#347FC4",
      "--navbar": "#5D536B",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#494155",
      "--navbar-accent": "#7D6B91",
      "--taskmenu": "#347FC4",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#989FCE",
      "--teal": "#347FC4",
      "--teal-soft": "#E1EFFA",
      "--coral": "#989FCE",
      "--coral-soft": "#F0F1F9",
      "--gradient-brand": "linear-gradient(135deg, #347FC4 0%, #7D6B91 100%)",
    },
    dark: {
      "--palette-c1": "#272838",
      "--palette-c2": "#5D536B",
      "--palette-c3": "#7D6B91",
      "--palette-c4": "#989FCE",
      "--palette-c5": "#347FC4",
      "--primary": "#347FC4",
      "--primary-foreground": "#ffffff",
      "--secondary": "#36374a",
      "--secondary-foreground": "#ffffff",
      "--accent": "#989FCE",
      "--accent-foreground": "#000000",
      "--background": "#12131C",
      "--foreground": "#ffffff",
      "--card": "#1c1d2b",
      "--card-foreground": "#ffffff",
      "--popover": "#1c1d2b",
      "--popover-foreground": "#ffffff",
      "--muted": "#27293d",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(152, 159, 206, 0.2)",
      "--input": "rgba(152, 159, 206, 0.24)",
      "--ring": "#347FC4",
      "--sidebar": "#1b1c28",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#347FC4",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#2f3147",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(152, 159, 206, 0.16)",
      "--sidebar-ring": "#347FC4",
      "--navbar": "#2e2538",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(152, 159, 206, 0.2)",
      "--navbar-accent": "#5D536B",
      "--taskmenu": "#347FC4",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#7D6B91",
      "--teal": "#347FC4",
      "--teal-soft": "#193754",
      "--coral": "#7D6B91",
      "--coral-soft": "#3b2f47",
      "--gradient-brand": "linear-gradient(135deg, #347FC4 0%, #989FCE 100%)",
    },
  },
  {
    id: "sage-mist",
    name: "Sage Mist",
    vibe: "Calm neutral tones transitioning into soft mint and pale sage green.",
    colors: ["#6B6054", "#929487", "#A1B0AB", "#C3DAC3", "#D5ECD4"],
    componentRoles: {
      sidebar: "Warm Earth (#6B6054)",
      navbar: "Olive Sage (#929487)",
      taskMenu: "Soft Mint Green (#576b5d)",
      cards: "Mint Cream (#D5ECD4)",
      accents: "Sage Mist (#A1B0AB)",
    },
    light: {
      "--palette-c1": "#6B6054",
      "--palette-c2": "#929487",
      "--palette-c3": "#A1B0AB",
      "--palette-c4": "#C3DAC3",
      "--palette-c5": "#D5ECD4",
      "--primary": "#576b5d",
      "--primary-foreground": "#ffffff",
      "--secondary": "#D5ECD4",
      "--secondary-foreground": "#1f2937",
      "--accent": "#A1B0AB",
      "--accent-foreground": "#1f2937",
      "--background": "#F6F8F6",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E5EFE5",
      "--muted-foreground": "#4b5563",
      "--border": "#D0DDD0",
      "--input": "#D0DDD0",
      "--ring": "#576b5d",
      "--sidebar": "#6B6054",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#D5ECD4",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#807466",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#534a40",
      "--sidebar-ring": "#D5ECD4",
      "--navbar": "#929487",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#7c7e73",
      "--navbar-accent": "#A1B0AB",
      "--taskmenu": "#576b5d",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#C3DAC3",
      "--teal": "#576b5d",
      "--teal-soft": "#E5EEE6",
      "--coral": "#929487",
      "--coral-soft": "#ECEEE9",
      "--gradient-brand": "linear-gradient(135deg, #6B6054 0%, #576b5d 100%)",
    },
    dark: {
      "--palette-c1": "#6B6054",
      "--palette-c2": "#929487",
      "--palette-c3": "#A1B0AB",
      "--palette-c4": "#C3DAC3",
      "--palette-c5": "#D5ECD4",
      "--primary": "#A1B0AB",
      "--primary-foreground": "#000000",
      "--secondary": "#2f3830",
      "--secondary-foreground": "#ffffff",
      "--accent": "#C3DAC3",
      "--accent-foreground": "#000000",
      "--background": "#111412",
      "--foreground": "#ffffff",
      "--card": "#1a211d",
      "--card-foreground": "#ffffff",
      "--popover": "#1a211d",
      "--popover-foreground": "#ffffff",
      "--muted": "#242d27",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(195, 218, 195, 0.2)",
      "--input": "rgba(195, 218, 195, 0.24)",
      "--ring": "#A1B0AB",
      "--sidebar": "#2e2924",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#A1B0AB",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#403a33",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(195, 218, 195, 0.16)",
      "--sidebar-ring": "#A1B0AB",
      "--navbar": "#3b3d37",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(161, 176, 171, 0.25)",
      "--navbar-accent": "#929487",
      "--taskmenu": "#C3DAC3",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#A1B0AB",
      "--teal": "#A1B0AB",
      "--teal-soft": "#2c3b36",
      "--coral": "#C3DAC3",
      "--coral-soft": "#2d3d2e",
      "--gradient-brand": "linear-gradient(135deg, #A1B0AB 0%, #C3DAC3 100%)",
    },
  },
  {
    id: "emerald-frost",
    name: "Emerald Frost",
    vibe: "High-contrast dark mode foundation with icy mint blue and rich emerald green.",
    colors: ["#000000", "#586F7C", "#B8DBD9", "#F4F4F9", "#04724D"],
    componentRoles: {
      sidebar: "Onyx Black (#000000)",
      navbar: "Slate Steel (#586F7C)",
      taskMenu: "Rich Emerald (#04724D)",
      cards: "Ice Blue Tint (#B8DBD9)",
      accents: "Frost White (#F4F4F9)",
    },
    light: {
      "--palette-c1": "#000000",
      "--palette-c2": "#586F7C",
      "--palette-c3": "#B8DBD9",
      "--palette-c4": "#F4F4F9",
      "--palette-c5": "#04724D",
      "--primary": "#04724D",
      "--primary-foreground": "#ffffff",
      "--secondary": "#B8DBD9",
      "--secondary-foreground": "#000000",
      "--accent": "#586F7C",
      "--accent-foreground": "#ffffff",
      "--background": "#F4F4F9",
      "--foreground": "#000000",
      "--card": "#FFFFFF",
      "--card-foreground": "#000000",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#000000",
      "--muted": "#E5E6F0",
      "--muted-foreground": "#4b5563",
      "--border": "#CCD4DD",
      "--input": "#CCD4DD",
      "--ring": "#04724D",
      "--sidebar": "#000000",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#04724D",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#22272B",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#1A1A1A",
      "--sidebar-ring": "#04724D",
      "--navbar": "#586F7C",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#475963",
      "--navbar-accent": "#04724D",
      "--taskmenu": "#04724D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#B8DBD9",
      "--teal": "#04724D",
      "--teal-soft": "#E0F4EC",
      "--coral": "#586F7C",
      "--coral-soft": "#E8EEF1",
      "--gradient-brand": "linear-gradient(135deg, #04724D 0%, #586F7C 100%)",
    },
    dark: {
      "--palette-c1": "#000000",
      "--palette-c2": "#586F7C",
      "--palette-c3": "#B8DBD9",
      "--palette-c4": "#F4F4F9",
      "--palette-c5": "#04724D",
      "--primary": "#04724D",
      "--primary-foreground": "#ffffff",
      "--secondary": "#202a2d",
      "--secondary-foreground": "#ffffff",
      "--accent": "#B8DBD9",
      "--accent-foreground": "#000000",
      "--background": "#080a0c",
      "--foreground": "#ffffff",
      "--card": "#111618",
      "--card-foreground": "#ffffff",
      "--popover": "#111618",
      "--popover-foreground": "#ffffff",
      "--muted": "#1a2124",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(184, 219, 217, 0.2)",
      "--input": "rgba(184, 219, 217, 0.24)",
      "--ring": "#04724D",
      "--sidebar": "#000000",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#04724D",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#14211e",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(184, 219, 217, 0.16)",
      "--sidebar-ring": "#04724D",
      "--navbar": "#1c2a30",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(88, 111, 124, 0.35)",
      "--navbar-accent": "#04724D",
      "--taskmenu": "#04724D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#B8DBD9",
      "--teal": "#04724D",
      "--teal-soft": "#0c3527",
      "--coral": "#B8DBD9",
      "--coral-soft": "#213636",
      "--gradient-brand": "linear-gradient(135deg, #04724D 0%, #B8DBD9 100%)",
    },
  },
  {
    id: "retro-muted",
    name: "Retro Muted",
    vibe: "Royal blue and teal balanced by warm sand beige and dusty rose.",
    colors: ["#4357AD", "#48A9A6", "#E4DFDA", "#D4B483", "#C1666B"],
    componentRoles: {
      sidebar: "Royal Slate (#4357AD)",
      navbar: "Retro Teal (#48A9A6)",
      taskMenu: "Dusty Rose (#C1666B)",
      cards: "Warm Sand (#E4DFDA)",
      accents: "Ochre Gold (#D4B483)",
    },
    light: {
      "--palette-c1": "#4357AD",
      "--palette-c2": "#48A9A6",
      "--palette-c3": "#E4DFDA",
      "--palette-c4": "#D4B483",
      "--palette-c5": "#C1666B",
      "--primary": "#4357AD",
      "--primary-foreground": "#ffffff",
      "--secondary": "#E4DFDA",
      "--secondary-foreground": "#1f2937",
      "--accent": "#C1666B",
      "--accent-foreground": "#ffffff",
      "--background": "#FAF7F3",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EFEBE6",
      "--muted-foreground": "#4b5563",
      "--border": "#DFD7CD",
      "--input": "#DFD7CD",
      "--ring": "#4357AD",
      "--sidebar": "#4357AD",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#C1666B",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#576AC4",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#34458D",
      "--sidebar-ring": "#C1666B",
      "--navbar": "#48A9A6",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#398885",
      "--navbar-accent": "#D4B483",
      "--taskmenu": "#C1666B",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#48A9A6",
      "--teal": "#48A9A6",
      "--teal-soft": "#E2F3F2",
      "--coral": "#C1666B",
      "--coral-soft": "#F8E9EA",
      "--gradient-brand": "linear-gradient(135deg, #4357AD 0%, #C1666B 100%)",
    },
    dark: {
      "--palette-c1": "#4357AD",
      "--palette-c2": "#48A9A6",
      "--palette-c3": "#E4DFDA",
      "--palette-c4": "#D4B483",
      "--palette-c5": "#C1666B",
      "--primary": "#48A9A6",
      "--primary-foreground": "#000000",
      "--secondary": "#3a3847",
      "--secondary-foreground": "#ffffff",
      "--accent": "#C1666B",
      "--accent-foreground": "#ffffff",
      "--background": "#111219",
      "--foreground": "#ffffff",
      "--card": "#1a1c26",
      "--card-foreground": "#ffffff",
      "--popover": "#1a1c26",
      "--popover-foreground": "#ffffff",
      "--muted": "#252736",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(228, 223, 218, 0.2)",
      "--input": "rgba(228, 223, 218, 0.24)",
      "--ring": "#48A9A6",
      "--sidebar": "#242f5e",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#48A9A6",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#344280",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(228, 223, 218, 0.16)",
      "--sidebar-ring": "#48A9A6",
      "--navbar": "#204a48",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(72, 169, 166, 0.3)",
      "--navbar-accent": "#C1666B",
      "--taskmenu": "#C1666B",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#48A9A6",
      "--teal": "#48A9A6",
      "--teal-soft": "#193d3c",
      "--coral": "#C1666B",
      "--coral-soft": "#422023",
      "--gradient-brand": "linear-gradient(135deg, #48A9A6 0%, #C1666B 100%)",
    },
  },
  {
    id: "peach-blossom",
    name: "Peach Blossom",
    vibe: "Soft periwinkle and deep navy warmed up by subtle peach tones.",
    colors: ["#3A405A", "#AEC5EB", "#F9DEC9", "#E9AFA3", "#685044"],
    componentRoles: {
      sidebar: "Navy Slate (#3A405A)",
      navbar: "Periwinkle (#AEC5EB)",
      taskMenu: "Coral Peach (#E9AFA3)",
      cards: "Peach Cream (#F9DEC9)",
      accents: "Walnut Brown (#685044)",
    },
    light: {
      "--palette-c1": "#3A405A",
      "--palette-c2": "#AEC5EB",
      "--palette-c3": "#F9DEC9",
      "--palette-c4": "#E9AFA3",
      "--palette-c5": "#685044",
      "--primary": "#3A405A",
      "--primary-foreground": "#ffffff",
      "--secondary": "#F9DEC9",
      "--secondary-foreground": "#1f2937",
      "--accent": "#E9AFA3",
      "--accent-foreground": "#1f2937",
      "--background": "#FDF9F5",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#F5E9DF",
      "--muted-foreground": "#4b5563",
      "--border": "#E8D8CC",
      "--input": "#E8D8CC",
      "--ring": "#3A405A",
      "--sidebar": "#3A405A",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#E9AFA3",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#4D5575",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#2c3145",
      "--sidebar-ring": "#E9AFA3",
      "--navbar": "#AEC5EB",
      "--navbar-foreground": "#1f2937",
      "--navbar-border": "#95aed4",
      "--navbar-accent": "#E9AFA3",
      "--taskmenu": "#E9AFA3",
      "--taskmenu-foreground": "#1f2937",
      "--taskmenu-accent": "#685044",
      "--teal": "#AEC5EB",
      "--teal-soft": "#EDF3FC",
      "--coral": "#E9AFA3",
      "--coral-soft": "#FCEFE7",
      "--gradient-brand": "linear-gradient(135deg, #3A405A 0%, #E9AFA3 100%)",
    },
    dark: {
      "--palette-c1": "#3A405A",
      "--palette-c2": "#AEC5EB",
      "--palette-c3": "#F9DEC9",
      "--palette-c4": "#E9AFA3",
      "--palette-c5": "#685044",
      "--primary": "#AEC5EB",
      "--primary-foreground": "#000000",
      "--secondary": "#3d3536",
      "--secondary-foreground": "#ffffff",
      "--accent": "#E9AFA3",
      "--accent-foreground": "#000000",
      "--background": "#12141C",
      "--foreground": "#ffffff",
      "--card": "#1a1c27",
      "--card-foreground": "#ffffff",
      "--popover": "#1a1c27",
      "--popover-foreground": "#ffffff",
      "--muted": "#272a39",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(233, 175, 163, 0.2)",
      "--input": "rgba(233, 175, 163, 0.24)",
      "--ring": "#AEC5EB",
      "--sidebar": "#232737",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#AEC5EB",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#34394f",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(233, 175, 163, 0.16)",
      "--sidebar-ring": "#AEC5EB",
      "--navbar": "#2e3650",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(174, 197, 235, 0.25)",
      "--navbar-accent": "#E9AFA3",
      "--taskmenu": "#E9AFA3",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#AEC5EB",
      "--teal": "#AEC5EB",
      "--teal-soft": "#20344f",
      "--coral": "#E9AFA3",
      "--coral-soft": "#452b27",
      "--gradient-brand": "linear-gradient(135deg, #AEC5EB 0%, #E9AFA3 100%)",
    },
  },
  {
    id: "neon-flare",
    name: "Neon Flare",
    vibe: "High-contrast black and off-white boosted by electric orange and fiery red.",
    colors: ["#000000", "#FFFFFC", "#BEB7A4", "#FF7F11", "#FF3F00"],
    componentRoles: {
      sidebar: "Obsidian Black (#000000)",
      navbar: "Electric Orange (#FF7F11)",
      taskMenu: "Fiery Red (#FF3F00)",
      cards: "Warm Off-White (#FFFFFC)",
      accents: "Khaki Sand (#BEB7A4)",
    },
    light: {
      "--palette-c1": "#000000",
      "--palette-c2": "#FFFFFC",
      "--palette-c3": "#BEB7A4",
      "--palette-c4": "#FF7F11",
      "--palette-c5": "#FF3F00",
      "--primary": "#FF3F00",
      "--primary-foreground": "#ffffff",
      "--secondary": "#BEB7A4",
      "--secondary-foreground": "#000000",
      "--accent": "#FF7F11",
      "--accent-foreground": "#ffffff",
      "--background": "#FFFFFC",
      "--foreground": "#000000",
      "--card": "#FFFFFF",
      "--card-foreground": "#000000",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#000000",
      "--muted": "#F0EDE5",
      "--muted-foreground": "#4b5563",
      "--border": "#DBD6C9",
      "--input": "#DBD6C9",
      "--ring": "#FF3F00",
      "--sidebar": "#000000",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FF3F00",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#222222",
      "--sidebar-accent-foreground": "#FF7F11",
      "--sidebar-border": "#1A1A1A",
      "--sidebar-ring": "#FF3F00",
      "--navbar": "#FF7F11",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#e06b00",
      "--navbar-accent": "#FF3F00",
      "--taskmenu": "#FF3F00",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#FF7F11",
      "--teal": "#FF7F11",
      "--teal-soft": "#FFF1E3",
      "--coral": "#FF3F00",
      "--coral-soft": "#FFE9E2",
      "--gradient-brand": "linear-gradient(135deg, #FF7F11 0%, #FF3F00 100%)",
    },
    dark: {
      "--palette-c1": "#000000",
      "--palette-c2": "#FFFFFC",
      "--palette-c3": "#BEB7A4",
      "--palette-c4": "#FF7F11",
      "--palette-c5": "#FF3F00",
      "--primary": "#FF7F11",
      "--primary-foreground": "#000000",
      "--secondary": "#29241e",
      "--secondary-foreground": "#ffffff",
      "--accent": "#FF3F00",
      "--accent-foreground": "#ffffff",
      "--background": "#080808",
      "--foreground": "#ffffff",
      "--card": "#121212",
      "--card-foreground": "#ffffff",
      "--popover": "#121212",
      "--popover-foreground": "#ffffff",
      "--muted": "#1c1c1c",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(255, 127, 17, 0.22)",
      "--input": "rgba(255, 127, 17, 0.26)",
      "--ring": "#FF7F11",
      "--sidebar": "#000000",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FF7F11",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#1f1812",
      "--sidebar-accent-foreground": "#FF7F11",
      "--sidebar-border": "rgba(255, 127, 17, 0.16)",
      "--sidebar-ring": "#FF7F11",
      "--navbar": "#381c03",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(255, 127, 17, 0.3)",
      "--navbar-accent": "#FF3F00",
      "--taskmenu": "#FF7F11",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#FF3F00",
      "--teal": "#FF7F11",
      "--teal-soft": "#3d2208",
      "--coral": "#FF3F00",
      "--coral-soft": "#451405",
      "--gradient-brand": "linear-gradient(135deg, #FF7F11 0%, #FF3F00 100%)",
    },
  },
  {
    id: "desert-cyan",
    name: "Desert Cyan",
    vibe: "Earthy caramel-tan tones offset by bright cyan and sky blue.",
    colors: ["#A57548", "#FCD7AD", "#F6C28B", "#5296A5", "#82DDF0"],
    componentRoles: {
      sidebar: "Caramel Brown (#A57548)",
      navbar: "Slate Cyan (#5296A5)",
      taskMenu: "Sky Cyan (#82DDF0)",
      cards: "Pale Honey (#FCD7AD)",
      accents: "Warm Peach Tan (#F6C28B)",
    },
    light: {
      "--palette-c1": "#A57548",
      "--palette-c2": "#FCD7AD",
      "--palette-c3": "#F6C28B",
      "--palette-c4": "#5296A5",
      "--palette-c5": "#82DDF0",
      "--primary": "#5296A5",
      "--primary-foreground": "#ffffff",
      "--secondary": "#FCD7AD",
      "--secondary-foreground": "#1f2937",
      "--accent": "#A57548",
      "--accent-foreground": "#ffffff",
      "--background": "#FAF7F2",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#F6E8D7",
      "--muted-foreground": "#4b5563",
      "--border": "#EAD3BC",
      "--input": "#EAD3BC",
      "--ring": "#5296A5",
      "--sidebar": "#A57548",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#82DDF0",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#BD8856",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#8E623A",
      "--sidebar-ring": "#82DDF0",
      "--navbar": "#5296A5",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#437e8b",
      "--navbar-accent": "#82DDF0",
      "--taskmenu": "#82DDF0",
      "--taskmenu-foreground": "#1f2937",
      "--taskmenu-accent": "#F6C28B",
      "--teal": "#82DDF0",
      "--teal-soft": "#E8FAFC",
      "--coral": "#F6C28B",
      "--coral-soft": "#FDF3E7",
      "--gradient-brand": "linear-gradient(135deg, #5296A5 0%, #82DDF0 100%)",
    },
    dark: {
      "--palette-c1": "#A57548",
      "--palette-c2": "#FCD7AD",
      "--palette-c3": "#F6C28B",
      "--palette-c4": "#5296A5",
      "--palette-c5": "#82DDF0",
      "--primary": "#82DDF0",
      "--primary-foreground": "#000000",
      "--secondary": "#3a2a1d",
      "--secondary-foreground": "#ffffff",
      "--accent": "#F6C28B",
      "--accent-foreground": "#000000",
      "--background": "#110e0b",
      "--foreground": "#ffffff",
      "--card": "#1a1511",
      "--card-foreground": "#ffffff",
      "--popover": "#1a1511",
      "--popover-foreground": "#ffffff",
      "--muted": "#261e18",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(130, 221, 240, 0.2)",
      "--input": "rgba(130, 221, 240, 0.24)",
      "--ring": "#82DDF0",
      "--sidebar": "#332314",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#82DDF0",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#4a3522",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(130, 221, 240, 0.16)",
      "--sidebar-ring": "#82DDF0",
      "--navbar": "#1c373e",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(130, 221, 240, 0.25)",
      "--navbar-accent": "#5296A5",
      "--taskmenu": "#82DDF0",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#F6C28B",
      "--teal": "#82DDF0",
      "--teal-soft": "#193940",
      "--coral": "#A57548",
      "--coral-soft": "#382315",
      "--gradient-brand": "linear-gradient(135deg, #82DDF0 0%, #5296A5 100%)",
    },
  },
  {
    id: "blue-lagoon",
    name: "Blue Lagoon",
    vibe: "Bright marine blues paired with tropical yellow and vibrant orange.",
    colors: ["#2364AA", "#3DA5D9", "#73BFB8", "#FEC601", "#EA7317"],
    componentRoles: {
      sidebar: "Marine Blue (#2364AA)",
      navbar: "Tropical Sky (#3DA5D9)",
      taskMenu: "Vibrant Orange (#EA7317)",
      cards: "Aqua Mint (#73BFB8)",
      accents: "Pop Yellow (#FEC601)",
    },
    light: {
      "--palette-c1": "#2364AA",
      "--palette-c2": "#3DA5D9",
      "--palette-c3": "#73BFB8",
      "--palette-c4": "#FEC601",
      "--palette-c5": "#EA7317",
      "--primary": "#2364AA",
      "--primary-foreground": "#ffffff",
      "--secondary": "#E4F4F7",
      "--secondary-foreground": "#1f2937",
      "--accent": "#EA7317",
      "--accent-foreground": "#ffffff",
      "--background": "#F5FAFD",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E2F0F7",
      "--muted-foreground": "#4b5563",
      "--border": "#CDE0ED",
      "--input": "#CDE0ED",
      "--ring": "#2364AA",
      "--sidebar": "#2364AA",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FEC601",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#2f79cb",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#1a4e85",
      "--sidebar-ring": "#FEC601",
      "--navbar": "#3DA5D9",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#2e90c0",
      "--navbar-accent": "#FEC601",
      "--taskmenu": "#EA7317",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#FEC601",
      "--teal": "#73BFB8",
      "--teal-soft": "#E9F7F6",
      "--coral": "#EA7317",
      "--coral-soft": "#FDEDE0",
      "--gradient-brand": "linear-gradient(135deg, #3DA5D9 0%, #EA7317 100%)",
    },
    dark: {
      "--palette-c1": "#2364AA",
      "--palette-c2": "#3DA5D9",
      "--palette-c3": "#73BFB8",
      "--palette-c4": "#FEC601",
      "--palette-c5": "#EA7317",
      "--primary": "#3DA5D9",
      "--primary-foreground": "#000000",
      "--secondary": "#1b3347",
      "--secondary-foreground": "#ffffff",
      "--accent": "#FEC601",
      "--accent-foreground": "#000000",
      "--background": "#0a1016",
      "--foreground": "#ffffff",
      "--card": "#101d28",
      "--card-foreground": "#ffffff",
      "--popover": "#101d28",
      "--popover-foreground": "#ffffff",
      "--muted": "#182736",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(61, 165, 217, 0.2)",
      "--input": "rgba(61, 165, 217, 0.24)",
      "--ring": "#3DA5D9",
      "--sidebar": "#163456",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FEC601",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#214772",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(61, 165, 217, 0.16)",
      "--sidebar-ring": "#FEC601",
      "--navbar": "#17445c",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(61, 165, 217, 0.3)",
      "--navbar-accent": "#EA7317",
      "--taskmenu": "#EA7317",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#FEC601",
      "--teal": "#73BFB8",
      "--teal-soft": "#193d39",
      "--coral": "#EA7317",
      "--coral-soft": "#3d210b",
      "--gradient-brand": "linear-gradient(135deg, #3DA5D9 0%, #FEC601 100%)",
    },
  },
  {
    id: "cyber-citrus",
    name: "Cyber Citrus",
    vibe: "Bold electric purple and dark crimson anchored by pop yellow.",
    colors: ["#540D6E", "#EE4266", "#FFD23F", "#F3FCF0", "#1F271B"],
    componentRoles: {
      sidebar: "Electric Purple (#540D6E)",
      navbar: "Crimson Red (#EE4266)",
      taskMenu: "Citrus Yellow (#FFD23F)",
      cards: "Mint Frost (#F3FCF0)",
      accents: "Forest Base (#1F271B)",
    },
    light: {
      "--palette-c1": "#540D6E",
      "--palette-c2": "#EE4266",
      "--palette-c3": "#FFD23F",
      "--palette-c4": "#F3FCF0",
      "--palette-c5": "#1F271B",
      "--primary": "#540D6E",
      "--primary-foreground": "#ffffff",
      "--secondary": "#F3FCF0",
      "--secondary-foreground": "#1f2937",
      "--accent": "#EE4266",
      "--accent-foreground": "#ffffff",
      "--background": "#F8FCF7",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EBF6E8",
      "--muted-foreground": "#4b5563",
      "--border": "#D2E5CD",
      "--input": "#D2E5CD",
      "--ring": "#540D6E",
      "--sidebar": "#540D6E",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FFD23F",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#6D158E",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#410955",
      "--sidebar-ring": "#FFD23F",
      "--navbar": "#EE4266",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#d63456",
      "--navbar-accent": "#FFD23F",
      "--taskmenu": "#FFD23F",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#EE4266",
      "--teal": "#FFD23F",
      "--teal-soft": "#FFF9E5",
      "--coral": "#EE4266",
      "--coral-soft": "#FDECEE",
      "--gradient-brand": "linear-gradient(135deg, #EE4266 0%, #FFD23F 100%)",
    },
    dark: {
      "--palette-c1": "#540D6E",
      "--palette-c2": "#EE4266",
      "--palette-c3": "#FFD23F",
      "--palette-c4": "#F3FCF0",
      "--palette-c5": "#1F271B",
      "--primary": "#EE4266",
      "--primary-foreground": "#ffffff",
      "--secondary": "#30133b",
      "--secondary-foreground": "#ffffff",
      "--accent": "#FFD23F",
      "--accent-foreground": "#000000",
      "--background": "#0e130c",
      "--foreground": "#ffffff",
      "--card": "#181f15",
      "--card-foreground": "#ffffff",
      "--popover": "#181f15",
      "--popover-foreground": "#ffffff",
      "--muted": "#232c1f",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(238, 66, 102, 0.22)",
      "--input": "rgba(238, 66, 102, 0.26)",
      "--ring": "#EE4266",
      "--sidebar": "#330843",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#FFD23F",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#4D0D65",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(238, 66, 102, 0.18)",
      "--sidebar-ring": "#FFD23F",
      "--navbar": "#47101c",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(238, 66, 102, 0.35)",
      "--navbar-accent": "#FFD23F",
      "--taskmenu": "#FFD23F",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#EE4266",
      "--teal": "#540D6E",
      "--teal-soft": "#330843",
      "--coral": "#EE4266",
      "--coral-soft": "#45131e",
      "--gradient-brand": "linear-gradient(135deg, #540D6E 0%, #EE4266 100%)",
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    vibe: "Deep teal combined with warm amber and metallic gold tones.",
    colors: ["#437C90", "#255957", "#EEEBD3", "#A98743", "#F7C548"],
    componentRoles: {
      sidebar: "Forest Teal (#255957)",
      navbar: "Steel Teal (#437C90)",
      taskMenu: "Golden Amber (#F7C548)",
      cards: "Warm Linen (#EEEBD3)",
      accents: "Antique Bronze (#A98743)",
    },
    light: {
      "--palette-c1": "#437C90",
      "--palette-c2": "#255957",
      "--palette-c3": "#EEEBD3",
      "--palette-c4": "#A98743",
      "--palette-c5": "#F7C548",
      "--primary": "#255957",
      "--primary-foreground": "#ffffff",
      "--secondary": "#EEEBD3",
      "--secondary-foreground": "#1f2937",
      "--accent": "#F7C548",
      "--accent-foreground": "#000000",
      "--background": "#FAF9F2",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EFEBD0",
      "--muted-foreground": "#4b5563",
      "--border": "#E0DCBD",
      "--input": "#E0DCBD",
      "--ring": "#255957",
      "--sidebar": "#255957",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#F7C548",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#33726F",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#1A4442",
      "--sidebar-ring": "#F7C548",
      "--navbar": "#437C90",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#366677",
      "--navbar-accent": "#F7C548",
      "--taskmenu": "#F7C548",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#A98743",
      "--teal": "#437C90",
      "--teal-soft": "#E8F1F4",
      "--coral": "#F7C548",
      "--coral-soft": "#FEF7E6",
      "--gradient-brand": "linear-gradient(135deg, #437C90 0%, #F7C548 100%)",
    },
    dark: {
      "--palette-c1": "#437C90",
      "--palette-c2": "#255957",
      "--palette-c3": "#EEEBD3",
      "--palette-c4": "#A98743",
      "--palette-c5": "#F7C548",
      "--primary": "#F7C548",
      "--primary-foreground": "#000000",
      "--secondary": "#1d3837",
      "--secondary-foreground": "#ffffff",
      "--accent": "#437C90",
      "--accent-foreground": "#ffffff",
      "--background": "#0c1514",
      "--foreground": "#ffffff",
      "--card": "#142221",
      "--card-foreground": "#ffffff",
      "--popover": "#142221",
      "--popover-foreground": "#ffffff",
      "--muted": "#1e3130",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(247, 197, 72, 0.2)",
      "--input": "rgba(247, 197, 72, 0.24)",
      "--ring": "#F7C548",
      "--sidebar": "#163635",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#F7C548",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#214E4D",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(247, 197, 72, 0.16)",
      "--sidebar-ring": "#F7C548",
      "--navbar": "#1c3c46",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(67, 124, 144, 0.35)",
      "--navbar-accent": "#F7C548",
      "--taskmenu": "#F7C548",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#437C90",
      "--teal": "#437C90",
      "--teal-soft": "#1a3842",
      "--coral": "#F7C548",
      "--coral-soft": "#42330e",
      "--gradient-brand": "linear-gradient(135deg, #255957 0%, #F7C548 100%)",
    },
  },
  {
    id: "midnight-berry",
    name: "Midnight Berry",
    vibe: "Slate blues offset by soft periwinkle and vivid magenta-pinks.",
    colors: ["#404E5C", "#4F6272", "#B7C3F3", "#DD7596", "#CF1259"],
    componentRoles: {
      sidebar: "Slate Charcoal (#404E5C)",
      navbar: "Slate Blue (#4F6272)",
      taskMenu: "Vivid Magenta (#CF1259)",
      cards: "Periwinkle Frost (#B7C3F3)",
      accents: "Rose Berry (#DD7596)",
    },
    light: {
      "--palette-c1": "#404E5C",
      "--palette-c2": "#4F6272",
      "--palette-c3": "#B7C3F3",
      "--palette-c4": "#DD7596",
      "--palette-c5": "#CF1259",
      "--primary": "#CF1259",
      "--primary-foreground": "#ffffff",
      "--secondary": "#EDF0FC",
      "--secondary-foreground": "#1f2937",
      "--accent": "#DD7596",
      "--accent-foreground": "#ffffff",
      "--background": "#F7F8FC",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E8ECF7",
      "--muted-foreground": "#4b5563",
      "--border": "#D5DBEC",
      "--input": "#D5DBEC",
      "--ring": "#CF1259",
      "--sidebar": "#404E5C",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CF1259",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#536475",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#313C47",
      "--sidebar-ring": "#CF1259",
      "--navbar": "#4F6272",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#3E4D5A",
      "--navbar-accent": "#DD7596",
      "--taskmenu": "#CF1259",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#DD7596",
      "--teal": "#B7C3F3",
      "--teal-soft": "#F2F5FD",
      "--coral": "#CF1259",
      "--coral-soft": "#FBE7EF",
      "--gradient-brand": "linear-gradient(135deg, #4F6272 0%, #CF1259 100%)",
    },
    dark: {
      "--palette-c1": "#404E5C",
      "--palette-c2": "#4F6272",
      "--palette-c3": "#B7C3F3",
      "--palette-c4": "#DD7596",
      "--palette-c5": "#CF1259",
      "--primary": "#DD7596",
      "--primary-foreground": "#ffffff",
      "--secondary": "#28303a",
      "--secondary-foreground": "#ffffff",
      "--accent": "#CF1259",
      "--accent-foreground": "#ffffff",
      "--background": "#0e1114",
      "--foreground": "#ffffff",
      "--card": "#171c22",
      "--card-foreground": "#ffffff",
      "--popover": "#171c22",
      "--popover-foreground": "#ffffff",
      "--muted": "#212830",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(221, 117, 150, 0.2)",
      "--input": "rgba(221, 117, 150, 0.24)",
      "--ring": "#DD7596",
      "--sidebar": "#232a32",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#DD7596",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#323C47",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(221, 117, 150, 0.16)",
      "--sidebar-ring": "#DD7596",
      "--navbar": "#2c3843",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(221, 117, 150, 0.25)",
      "--navbar-accent": "#CF1259",
      "--taskmenu": "#CF1259",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#DD7596",
      "--teal": "#B7C3F3",
      "--teal-soft": "#212845",
      "--coral": "#CF1259",
      "--coral-soft": "#450920",
      "--gradient-brand": "linear-gradient(135deg, #DD7596 0%, #CF1259 100%)",
    },
  },
  {
    id: "blush-mint",
    name: "Blush Mint",
    vibe: "Delicate pastel pinks and rich plum balanced by fresh sage mint.",
    colors: ["#512D38", "#B27092", "#F4BFDB", "#FFE9F3", "#87BAAB"],
    componentRoles: {
      sidebar: "Deep Plum (#512D38)",
      navbar: "Fresh Sage Mint (#87BAAB)",
      taskMenu: "Muted Rose (#B27092)",
      cards: "Soft Blush (#FFE9F3)",
      accents: "Orchid Lilac (#F4BFDB)",
    },
    light: {
      "--palette-c1": "#512D38",
      "--palette-c2": "#B27092",
      "--palette-c3": "#F4BFDB",
      "--palette-c4": "#FFE9F3",
      "--palette-c5": "#87BAAB",
      "--primary": "#512D38",
      "--primary-foreground": "#ffffff",
      "--secondary": "#FFE9F3",
      "--secondary-foreground": "#1f2937",
      "--accent": "#87BAAB",
      "--accent-foreground": "#1f2937",
      "--background": "#FDF9FA",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#FBE9F2",
      "--muted-foreground": "#4b5563",
      "--border": "#EAD3DE",
      "--input": "#EAD3DE",
      "--ring": "#512D38",
      "--sidebar": "#512D38",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#87BAAB",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#6A3B4A",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#3F232C",
      "--sidebar-ring": "#87BAAB",
      "--navbar": "#87BAAB",
      "--navbar-foreground": "#1f2937",
      "--navbar-border": "#71A193",
      "--navbar-accent": "#B27092",
      "--taskmenu": "#B27092",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#87BAAB",
      "--teal": "#87BAAB",
      "--teal-soft": "#EFF7F5",
      "--coral": "#B27092",
      "--coral-soft": "#FAEEF4",
      "--gradient-brand": "linear-gradient(135deg, #87BAAB 0%, #B27092 100%)",
    },
    dark: {
      "--palette-c1": "#512D38",
      "--palette-c2": "#B27092",
      "--palette-c3": "#F4BFDB",
      "--palette-c4": "#FFE9F3",
      "--palette-c5": "#87BAAB",
      "--primary": "#F4BFDB",
      "--primary-foreground": "#000000",
      "--secondary": "#3d222b",
      "--secondary-foreground": "#ffffff",
      "--accent": "#87BAAB",
      "--accent-foreground": "#000000",
      "--background": "#140c0f",
      "--foreground": "#ffffff",
      "--card": "#1f1318",
      "--card-foreground": "#ffffff",
      "--popover": "#1f1318",
      "--popover-foreground": "#ffffff",
      "--muted": "#2a1b21",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(244, 191, 219, 0.2)",
      "--input": "rgba(244, 191, 219, 0.24)",
      "--ring": "#F4BFDB",
      "--sidebar": "#2e181f",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#F4BFDB",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#45242F",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(244, 191, 219, 0.16)",
      "--sidebar-ring": "#F4BFDB",
      "--navbar": "#274039",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(135, 186, 171, 0.3)",
      "--navbar-accent": "#B27092",
      "--taskmenu": "#B27092",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#87BAAB",
      "--teal": "#87BAAB",
      "--teal-soft": "#213832",
      "--coral": "#B27092",
      "--coral-soft": "#3d1f2d",
      "--gradient-brand": "linear-gradient(135deg, #B27092 0%, #87BAAB 100%)",
    },
  },
  {
    id: "arctic-breeze",
    name: "Arctic Breeze",
    vibe: "Dark-to-light blue progression anchored by an icy aqua cyan.",
    colors: ["#161925", "#23395B", "#406E8E", "#8EA8C3", "#CBF7ED"],
    componentRoles: {
      sidebar: "Polar Navy (#161925)",
      navbar: "Steel Blue (#23395B)",
      taskMenu: "Icy Cyan (#CBF7ED)",
      cards: "Ocean Blue Tint (#406E8E)",
      accents: "Sky Slate (#8EA8C3)",
    },
    light: {
      "--palette-c1": "#161925",
      "--palette-c2": "#23395B",
      "--palette-c3": "#406E8E",
      "--palette-c4": "#8EA8C3",
      "--palette-c5": "#CBF7ED",
      "--primary": "#23395B",
      "--primary-foreground": "#ffffff",
      "--secondary": "#CBF7ED",
      "--secondary-foreground": "#1f2937",
      "--accent": "#406E8E",
      "--accent-foreground": "#ffffff",
      "--background": "#F5F8FA",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E5EEF3",
      "--muted-foreground": "#4b5563",
      "--border": "#D0E0EA",
      "--input": "#D0E0EA",
      "--ring": "#23395B",
      "--sidebar": "#161925",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CBF7ED",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#252B3D",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#10121B",
      "--sidebar-ring": "#CBF7ED",
      "--navbar": "#23395B",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#1C2D48",
      "--navbar-accent": "#CBF7ED",
      "--taskmenu": "#CBF7ED",
      "--taskmenu-foreground": "#1f2937",
      "--taskmenu-accent": "#406E8E",
      "--teal": "#CBF7ED",
      "--teal-soft": "#E8FAF5",
      "--coral": "#8EA8C3",
      "--coral-soft": "#F0F4F8",
      "--gradient-brand": "linear-gradient(135deg, #23395B 0%, #CBF7ED 100%)",
    },
    dark: {
      "--palette-c1": "#161925",
      "--palette-c2": "#23395B",
      "--palette-c3": "#406E8E",
      "--palette-c4": "#8EA8C3",
      "--palette-c5": "#CBF7ED",
      "--primary": "#CBF7ED",
      "--primary-foreground": "#000000",
      "--secondary": "#1d2e47",
      "--secondary-foreground": "#ffffff",
      "--accent": "#8EA8C3",
      "--accent-foreground": "#000000",
      "--background": "#090b10",
      "--foreground": "#ffffff",
      "--card": "#11141e",
      "--card-foreground": "#ffffff",
      "--popover": "#11141e",
      "--popover-foreground": "#ffffff",
      "--muted": "#181e2b",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(203, 247, 237, 0.2)",
      "--input": "rgba(203, 247, 237, 0.24)",
      "--ring": "#CBF7ED",
      "--sidebar": "#10121B",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CBF7ED",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#1F2538",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(203, 247, 237, 0.16)",
      "--sidebar-ring": "#CBF7ED",
      "--navbar": "#18263D",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(203, 247, 237, 0.25)",
      "--navbar-accent": "#406E8E",
      "--taskmenu": "#CBF7ED",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#8EA8C3",
      "--teal": "#CBF7ED",
      "--teal-soft": "#133b32",
      "--coral": "#406E8E",
      "--coral-soft": "#193547",
      "--gradient-brand": "linear-gradient(135deg, #406E8E 0%, #CBF7ED 100%)",
    },
  },
  {
    id: "terracotta-sunset",
    name: "Terracotta Sunset",
    vibe: "Cool slate greys grounded with warm sandy beige and earthy ochre tones.",
    colors: ["#646E78", "#8D98A7", "#DCCCBB", "#EAB464", "#A7754D"],
    componentRoles: {
      sidebar: "Slate Charcoal (#646E78)",
      navbar: "Cool Slate (#8D98A7)",
      taskMenu: "Terracotta Clay (#A7754D)",
      cards: "Warm Sand (#DCCCBB)",
      accents: "Ochre Gold (#EAB464)",
    },
    light: {
      "--palette-c1": "#646E78",
      "--palette-c2": "#8D98A7",
      "--palette-c3": "#DCCCBB",
      "--palette-c4": "#EAB464",
      "--palette-c5": "#A7754D",
      "--primary": "#A7754D",
      "--primary-foreground": "#ffffff",
      "--secondary": "#DCCCBB",
      "--secondary-foreground": "#1f2937",
      "--accent": "#EAB464",
      "--accent-foreground": "#000000",
      "--background": "#FAF7F3",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EFE9E0",
      "--muted-foreground": "#4b5563",
      "--border": "#DDD3C6",
      "--input": "#DDD3C6",
      "--ring": "#A7754D",
      "--sidebar": "#646E78",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#EAB464",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#76828D",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#535B64",
      "--sidebar-ring": "#EAB464",
      "--navbar": "#8D98A7",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#758090",
      "--navbar-accent": "#EAB464",
      "--taskmenu": "#A7754D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#EAB464",
      "--teal": "#EAB464",
      "--teal-soft": "#FDF4E6",
      "--coral": "#A7754D",
      "--coral-soft": "#F6EDE5",
      "--gradient-brand": "linear-gradient(135deg, #8D98A7 0%, #A7754D 100%)",
    },
    dark: {
      "--palette-c1": "#646E78",
      "--palette-c2": "#8D98A7",
      "--palette-c3": "#DCCCBB",
      "--palette-c4": "#EAB464",
      "--palette-c5": "#A7754D",
      "--primary": "#EAB464",
      "--primary-foreground": "#000000",
      "--secondary": "#3d3229",
      "--secondary-foreground": "#ffffff",
      "--accent": "#A7754D",
      "--accent-foreground": "#ffffff",
      "--background": "#111214",
      "--foreground": "#ffffff",
      "--card": "#1a1d21",
      "--card-foreground": "#ffffff",
      "--popover": "#1a1d21",
      "--popover-foreground": "#ffffff",
      "--muted": "#24272c",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(234, 180, 100, 0.2)",
      "--input": "rgba(234, 180, 100, 0.24)",
      "--ring": "#EAB464",
      "--sidebar": "#22272C",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#EAB464",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#333A42",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(234, 180, 100, 0.16)",
      "--sidebar-ring": "#EAB464",
      "--navbar": "#313840",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(234, 180, 100, 0.25)",
      "--navbar-accent": "#A7754D",
      "--taskmenu": "#A7754D",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#EAB464",
      "--teal": "#EAB464",
      "--teal-soft": "#453215",
      "--coral": "#A7754D",
      "--coral-soft": "#3d2516",
      "--gradient-brand": "linear-gradient(135deg, #A7754D 0%, #EAB464 100%)",
    },
  },
  {
    id: "olive-forest",
    name: "Olive Forest",
    vibe: "Muted dark slate pairing naturally with vibrant lime-olive greens.",
    colors: ["#45425A", "#575C55", "#6C7D47", "#96A13A", "#ACC12F"],
    componentRoles: {
      sidebar: "Dark Slate (#45425A)",
      navbar: "Forest Slate (#575C55)",
      taskMenu: "Vibrant Lime (#ACC12F)",
      cards: "Deep Olive (#6C7D47)",
      accents: "Lime Olive (#96A13A)",
    },
    light: {
      "--palette-c1": "#45425A",
      "--palette-c2": "#575C55",
      "--palette-c3": "#6C7D47",
      "--palette-c4": "#96A13A",
      "--palette-c5": "#ACC12F",
      "--primary": "#6C7D47",
      "--primary-foreground": "#ffffff",
      "--secondary": "#F3F7DE",
      "--secondary-foreground": "#1f2937",
      "--accent": "#ACC12F",
      "--accent-foreground": "#000000",
      "--background": "#F7F8F4",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#E8ECD7",
      "--muted-foreground": "#4b5563",
      "--border": "#D2DCBC",
      "--input": "#D2DCBC",
      "--ring": "#6C7D47",
      "--sidebar": "#45425A",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#ACC12F",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#595574",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#363346",
      "--sidebar-ring": "#ACC12F",
      "--navbar": "#575C55",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#464A45",
      "--navbar-accent": "#ACC12F",
      "--taskmenu": "#ACC12F",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#6C7D47",
      "--teal": "#96A13A",
      "--teal-soft": "#F5F7E6",
      "--coral": "#ACC12F",
      "--coral-soft": "#F8FCE5",
      "--gradient-brand": "linear-gradient(135deg, #6C7D47 0%, #ACC12F 100%)",
    },
    dark: {
      "--palette-c1": "#45425A",
      "--palette-c2": "#575C55",
      "--palette-c3": "#6C7D47",
      "--palette-c4": "#96A13A",
      "--palette-c5": "#ACC12F",
      "--primary": "#ACC12F",
      "--primary-foreground": "#000000",
      "--secondary": "#2c3320",
      "--secondary-foreground": "#ffffff",
      "--accent": "#96A13A",
      "--accent-foreground": "#ffffff",
      "--background": "#0f0e13",
      "--foreground": "#ffffff",
      "--card": "#181720",
      "--card-foreground": "#ffffff",
      "--popover": "#181720",
      "--popover-foreground": "#ffffff",
      "--muted": "#23212d",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(172, 193, 47, 0.22)",
      "--input": "rgba(172, 193, 47, 0.26)",
      "--ring": "#ACC12F",
      "--sidebar": "#262432",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#ACC12F",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#383649",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(172, 193, 47, 0.18)",
      "--sidebar-ring": "#ACC12F",
      "--navbar": "#2F312E",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(172, 193, 47, 0.25)",
      "--navbar-accent": "#96A13A",
      "--taskmenu": "#ACC12F",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#6C7D47",
      "--teal": "#ACC12F",
      "--teal-soft": "#343d0b",
      "--coral": "#96A13A",
      "--coral-soft": "#30360f",
      "--gradient-brand": "linear-gradient(135deg, #575C55 0%, #ACC12F 100%)",
    },
  },
  {
    id: "autumn-spices",
    name: "Autumn Spices",
    vibe: "Rich maroon-crimson and burnt orange fading into soft, sunny greens.",
    colors: ["#561D25", "#CE8147", "#ECDD7B", "#D3E298", "#CDE7BE"],
    componentRoles: {
      sidebar: "Maroon Crimson (#561D25)",
      navbar: "Burnt Orange (#CE8147)",
      taskMenu: "Golden Maize (#ECDD7B)",
      cards: "Celadon Green (#CDE7BE)",
      accents: "Spring Olive (#D3E298)",
    },
    light: {
      "--palette-c1": "#561D25",
      "--palette-c2": "#CE8147",
      "--palette-c3": "#ECDD7B",
      "--palette-c4": "#D3E298",
      "--palette-c5": "#CDE7BE",
      "--primary": "#CE8147",
      "--primary-foreground": "#ffffff",
      "--secondary": "#CDE7BE",
      "--secondary-foreground": "#1f2937",
      "--accent": "#561D25",
      "--accent-foreground": "#ffffff",
      "--background": "#FAF7F2",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#F3E8D7",
      "--muted-foreground": "#4b5563",
      "--border": "#E5D2B8",
      "--input": "#E5D2B8",
      "--ring": "#CE8147",
      "--sidebar": "#561D25",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#ECDD7B",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#732732",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#43161D",
      "--sidebar-ring": "#ECDD7B",
      "--navbar": "#CE8147",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#B56E39",
      "--navbar-accent": "#ECDD7B",
      "--taskmenu": "#ECDD7B",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#CE8147",
      "--teal": "#D3E298",
      "--teal-soft": "#F6FAE9",
      "--coral": "#CE8147",
      "--coral-soft": "#FBF0E7",
      "--gradient-brand": "linear-gradient(135deg, #CE8147 0%, #ECDD7B 100%)",
    },
    dark: {
      "--palette-c1": "#561D25",
      "--palette-c2": "#CE8147",
      "--palette-c3": "#ECDD7B",
      "--palette-c4": "#D3E298",
      "--palette-c5": "#CDE7BE",
      "--primary": "#CE8147",
      "--primary-foreground": "#ffffff",
      "--secondary": "#3d2219",
      "--secondary-foreground": "#ffffff",
      "--accent": "#ECDD7B",
      "--accent-foreground": "#000000",
      "--background": "#11080a",
      "--foreground": "#ffffff",
      "--card": "#1a0e10",
      "--card-foreground": "#ffffff",
      "--popover": "#1a0e10",
      "--popover-foreground": "#ffffff",
      "--muted": "#251518",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(206, 129, 71, 0.22)",
      "--input": "rgba(206, 129, 71, 0.26)",
      "--ring": "#CE8147",
      "--sidebar": "#330F14",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CE8147",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#4D161E",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(206, 129, 71, 0.18)",
      "--sidebar-ring": "#CE8147",
      "--navbar": "#3D1E11",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(206, 129, 71, 0.3)",
      "--navbar-accent": "#ECDD7B",
      "--taskmenu": "#ECDD7B",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#CE8147",
      "--teal": "#ECDD7B",
      "--teal-soft": "#3d3714",
      "--coral": "#CE8147",
      "--coral-soft": "#452410",
      "--gradient-brand": "linear-gradient(135deg, #561D25 0%, #CE8147 100%)",
    },
  },
  {
    id: "warm-clay",
    name: "Warm Clay",
    vibe: "Cozy mauve-pinks and warm beige highlights subtly cooled by ice blue.",
    colors: ["#584B53", "#9D5C63", "#D6E3F8", "#FEF5EF", "#E4BB97"],
    componentRoles: {
      sidebar: "Charcoal Mauve (#584B53)",
      navbar: "Dusty Berry (#9D5C63)",
      taskMenu: "Warm Biscuit (#E4BB97)",
      cards: "Soft Cream (#FEF5EF)",
      accents: "Ice Sky Blue (#D6E3F8)",
    },
    light: {
      "--palette-c1": "#584B53",
      "--palette-c2": "#9D5C63",
      "--palette-c3": "#D6E3F8",
      "--palette-c4": "#FEF5EF",
      "--palette-c5": "#E4BB97",
      "--primary": "#9D5C63",
      "--primary-foreground": "#ffffff",
      "--secondary": "#D6E3F8",
      "--secondary-foreground": "#1f2937",
      "--accent": "#E4BB97",
      "--accent-foreground": "#1f2937",
      "--background": "#FAF5F1",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#F3E4DC",
      "--muted-foreground": "#4b5563",
      "--border": "#E4D0C5",
      "--input": "#E4D0C5",
      "--ring": "#9D5C63",
      "--sidebar": "#584B53",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#E4BB97",
      "--sidebar-primary-foreground": "#1f2937",
      "--sidebar-accent": "#6D5D67",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#463B42",
      "--sidebar-ring": "#E4BB97",
      "--navbar": "#9D5C63",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#854D53",
      "--navbar-accent": "#D6E3F8",
      "--taskmenu": "#E4BB97",
      "--taskmenu-foreground": "#1f2937",
      "--taskmenu-accent": "#9D5C63",
      "--teal": "#D6E3F8",
      "--teal-soft": "#F2F7FD",
      "--coral": "#9D5C63",
      "--coral-soft": "#F9EBED",
      "--gradient-brand": "linear-gradient(135deg, #9D5C63 0%, #E4BB97 100%)",
    },
    dark: {
      "--palette-c1": "#584B53",
      "--palette-c2": "#9D5C63",
      "--palette-c3": "#D6E3F8",
      "--palette-c4": "#FEF5EF",
      "--palette-c5": "#E4BB97",
      "--primary": "#E4BB97",
      "--primary-foreground": "#000000",
      "--secondary": "#3d2b31",
      "--secondary-foreground": "#ffffff",
      "--accent": "#9D5C63",
      "--accent-foreground": "#ffffff",
      "--background": "#110e10",
      "--foreground": "#ffffff",
      "--card": "#1a1618",
      "--card-foreground": "#ffffff",
      "--popover": "#1a1618",
      "--popover-foreground": "#ffffff",
      "--muted": "#251e22",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(228, 187, 151, 0.2)",
      "--input": "rgba(228, 187, 151, 0.24)",
      "--ring": "#E4BB97",
      "--sidebar": "#2E242A",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#E4BB97",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#42353D",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(228, 187, 151, 0.16)",
      "--sidebar-ring": "#E4BB97",
      "--navbar": "#381F23",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(157, 92, 99, 0.35)",
      "--navbar-accent": "#E4BB97",
      "--taskmenu": "#E4BB97",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#D6E3F8",
      "--teal": "#D6E3F8",
      "--teal-soft": "#1e2c40",
      "--coral": "#9D5C63",
      "--coral-soft": "#3f1e23",
      "--gradient-brand": "linear-gradient(135deg, #9D5C63 0%, #E4BB97 100%)",
    },
  },
  {
    id: "pine-ember",
    name: "Pine Ember",
    vibe: "High-contrast dark forest greens, terracotta red, and warm clay.",
    colors: ["#D8CBC7", "#CC3F0C", "#9A6D38", "#33673B", "#19231A"],
    componentRoles: {
      sidebar: "Forest Onyx (#19231A)",
      navbar: "Deep Pine (#33673B)",
      taskMenu: "Terracotta Red (#CC3F0C)",
      cards: "Clay Frost (#D8CBC7)",
      accents: "Amber Wood (#9A6D38)",
    },
    light: {
      "--palette-c1": "#19231A",
      "--palette-c2": "#33673B",
      "--palette-c3": "#9A6D38",
      "--palette-c4": "#CC3F0C",
      "--palette-c5": "#D8CBC7",
      "--primary": "#33673B",
      "--primary-foreground": "#ffffff",
      "--secondary": "#D8CBC7",
      "--secondary-foreground": "#000000",
      "--accent": "#CC3F0C",
      "--accent-foreground": "#ffffff",
      "--background": "#FAF7F6",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EFE6E3",
      "--muted-foreground": "#4b5563",
      "--border": "#DDD1CD",
      "--input": "#DDD1CD",
      "--ring": "#33673B",
      "--sidebar": "#19231A",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CC3F0C",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#2B3B2D",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#131B14",
      "--sidebar-ring": "#CC3F0C",
      "--navbar": "#33673B",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#28522F",
      "--navbar-accent": "#CC3F0C",
      "--taskmenu": "#CC3F0C",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#9A6D38",
      "--teal": "#33673B",
      "--teal-soft": "#E8F3EA",
      "--coral": "#CC3F0C",
      "--coral-soft": "#FCEBE5",
      "--gradient-brand": "linear-gradient(135deg, #33673B 0%, #CC3F0C 100%)",
    },
    dark: {
      "--palette-c1": "#19231A",
      "--palette-c2": "#33673B",
      "--palette-c3": "#9A6D38",
      "--palette-c4": "#CC3F0C",
      "--palette-c5": "#D8CBC7",
      "--primary": "#CC3F0C",
      "--primary-foreground": "#ffffff",
      "--secondary": "#213626",
      "--secondary-foreground": "#ffffff",
      "--accent": "#9A6D38",
      "--accent-foreground": "#ffffff",
      "--background": "#0b0f0c",
      "--foreground": "#ffffff",
      "--card": "#131c15",
      "--card-foreground": "#ffffff",
      "--popover": "#131c15",
      "--popover-foreground": "#ffffff",
      "--muted": "#1a271c",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(204, 63, 12, 0.22)",
      "--input": "rgba(204, 63, 12, 0.26)",
      "--ring": "#CC3F0C",
      "--sidebar": "#121913",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#CC3F0C",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#1F2A20",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(204, 63, 12, 0.18)",
      "--sidebar-ring": "#CC3F0C",
      "--navbar": "#1C3821",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(51, 103, 59, 0.35)",
      "--navbar-accent": "#CC3F0C",
      "--taskmenu": "#CC3F0C",
      "--taskmenu-foreground": "#ffffff",
      "--taskmenu-accent": "#9A6D38",
      "--teal": "#33673B",
      "--teal-soft": "#183b1f",
      "--coral": "#CC3F0C",
      "--coral-soft": "#451707",
      "--gradient-brand": "linear-gradient(135deg, #33673B 0%, #CC3F0C 100%)",
    },
  },
  {
    id: "bio-lime",
    name: "Bio Lime",
    vibe: "Monochromatic shades of deep foliage green paired with bright chartreuse.",
    colors: ["#243010", "#87A330", "#A1C349", "#CAD593", "#2A3C24"],
    componentRoles: {
      sidebar: "Deep Foliage (#243010)",
      navbar: "Forest Pine (#2A3C24)",
      taskMenu: "Bright Chartreuse (#A1C349)",
      cards: "Pale Lime Tint (#CAD593)",
      accents: "Meadow Olive (#87A330)",
    },
    light: {
      "--palette-c1": "#243010",
      "--palette-c2": "#87A330",
      "--palette-c3": "#A1C349",
      "--palette-c4": "#CAD593",
      "--palette-c5": "#2A3C24",
      "--primary": "#243010",
      "--primary-foreground": "#ffffff",
      "--secondary": "#CAD593",
      "--secondary-foreground": "#1f2937",
      "--accent": "#87A330",
      "--accent-foreground": "#ffffff",
      "--background": "#F9FAF4",
      "--foreground": "#1f2937",
      "--card": "#FFFFFF",
      "--card-foreground": "#1f2937",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1f2937",
      "--muted": "#EEF4DB",
      "--muted-foreground": "#4b5563",
      "--border": "#D8E3B8",
      "--input": "#D8E3B8",
      "--ring": "#87A330",
      "--sidebar": "#243010",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#A1C349",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#384A1A",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "#1B240C",
      "--sidebar-ring": "#A1C349",
      "--navbar": "#2A3C24",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "#1E2B19",
      "--navbar-accent": "#A1C349",
      "--taskmenu": "#A1C349",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#87A330",
      "--teal": "#A1C349",
      "--teal-soft": "#F2F8E1",
      "--coral": "#87A330",
      "--coral-soft": "#EDF4D4",
      "--gradient-brand": "linear-gradient(135deg, #2A3C24 0%, #A1C349 100%)",
    },
    dark: {
      "--palette-c1": "#243010",
      "--palette-c2": "#87A330",
      "--palette-c3": "#A1C349",
      "--palette-c4": "#CAD593",
      "--palette-c5": "#2A3C24",
      "--primary": "#A1C349",
      "--primary-foreground": "#000000",
      "--secondary": "#304222",
      "--secondary-foreground": "#ffffff",
      "--accent": "#87A330",
      "--accent-foreground": "#ffffff",
      "--background": "#0a0e05",
      "--foreground": "#ffffff",
      "--card": "#131b0b",
      "--card-foreground": "#ffffff",
      "--popover": "#131b0b",
      "--popover-foreground": "#ffffff",
      "--muted": "#1c2710",
      "--muted-foreground": "#d1d5db",
      "--border": "rgba(161, 195, 73, 0.22)",
      "--input": "rgba(161, 195, 73, 0.26)",
      "--ring": "#A1C349",
      "--sidebar": "#1B240C",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-primary": "#A1C349",
      "--sidebar-primary-foreground": "#000000",
      "--sidebar-accent": "#2B3913",
      "--sidebar-accent-foreground": "#ffffff",
      "--sidebar-border": "rgba(161, 195, 73, 0.18)",
      "--sidebar-ring": "#A1C349",
      "--navbar": "#1C2818",
      "--navbar-foreground": "#ffffff",
      "--navbar-border": "rgba(161, 195, 73, 0.25)",
      "--navbar-accent": "#87A330",
      "--taskmenu": "#A1C349",
      "--taskmenu-foreground": "#000000",
      "--taskmenu-accent": "#87A330",
      "--teal": "#A1C349",
      "--teal-soft": "#283a0e",
      "--coral": "#87A330",
      "--coral-soft": "#2e3a0c",
      "--gradient-brand": "linear-gradient(135deg, #2A3C24 0%, #A1C349 100%)",
    },
  },
];

export function getPalette(id?: string): PaletteDefinition {
  return PALETTES.find((p) => p.id === id) || PALETTES[0];
}

export function applyThemePalette(paletteId?: string, isDark: boolean = false) {
  if (typeof document === "undefined") return;
  const palette = getPalette(paletteId);
  const vars = isDark ? palette.dark : palette.light;
  const root = document.documentElement;

  root.setAttribute("data-theme", palette.id);

  // Set explicit custom palette tokens
  for (const [key, value] of Object.entries(vars)) {
    root.style.setProperty(key, value);
  }

  // Set high-fidelity KPI Card Tokens matching NexaVerse reference design
  const kpi1 = vars["--kpi-1-bg"] || palette.colors[1];
  const kpi2 = vars["--kpi-2-bg"] || palette.colors[2];
  const kpi3 = vars["--kpi-3-bg"] || palette.colors[3];
  const kpi4 = vars["--kpi-4-bg"] || palette.colors[0];

  root.style.setProperty("--kpi-1-bg", kpi1);
  root.style.setProperty("--kpi-1-fg", getOptimalTextColor(kpi1));
  root.style.setProperty("--kpi-1-muted", getOptimalTextColor(kpi1, "muted"));

  root.style.setProperty("--kpi-2-bg", kpi2);
  root.style.setProperty("--kpi-2-fg", getOptimalTextColor(kpi2));
  root.style.setProperty("--kpi-2-muted", getOptimalTextColor(kpi2, "muted"));

  root.style.setProperty("--kpi-3-bg", kpi3);
  root.style.setProperty("--kpi-3-fg", getOptimalTextColor(kpi3));
  root.style.setProperty("--kpi-3-muted", getOptimalTextColor(kpi3, "muted"));

  root.style.setProperty("--kpi-4-bg", kpi4);
  root.style.setProperty("--kpi-4-fg", getOptimalTextColor(kpi4));
  root.style.setProperty("--kpi-4-muted", getOptimalTextColor(kpi4, "muted"));
}
