/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSubscriptionRouteImport } from './routes/admin.subscription'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalaryRevisionRouteImport } from './routes/admin.salary-revision'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRenewalsRouteImport } from './routes/admin.renewals'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminOrgRouteImport } from './routes/admin.org'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminLifecycleRouteImport } from './routes/admin.lifecycle'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminComplianceDocsRouteImport } from './routes/admin.compliance-docs'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionRoute = AdminSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalaryRevisionRoute = AdminSalaryRevisionRouteImport.update({
  id: '/salary-revision',
  path: '/salary-revision',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRenewalsRoute = AdminRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgRoute = AdminOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLifecycleRoute = AdminLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceDocsRoute = AdminComplianceDocsRouteImport.update({
  id: '/compliance-docs',
  path: '/compliance-docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/compliance-docs': typeof AdminComplianceDocsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-revision': typeof AdminSalaryRevisionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/compliance-docs': typeof AdminComplianceDocsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-revision': typeof AdminSalaryRevisionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/compliance-docs': typeof AdminComplianceDocsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/org': typeof AdminOrgRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/salary-revision': typeof AdminSalaryRevisionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/super-admin'
    | '/admin/ai'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/compliance'
    | '/admin/compliance-docs'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/lifecycle'
    | '/admin/notices'
    | '/admin/org'
    | '/admin/payroll'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/salary-revision'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/super-admin'
    | '/admin/ai'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/compliance'
    | '/admin/compliance-docs'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/lifecycle'
    | '/admin/notices'
    | '/admin/org'
    | '/admin/payroll'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/salary-revision'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/super-admin'
    | '/admin/ai'
    | '/admin/assets'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/compliance'
    | '/admin/compliance-docs'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/lifecycle'
    | '/admin/notices'
    | '/admin/org'
    | '/admin/payroll'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/salary-revision'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SuperAdminRoute: typeof SuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription': {
      id: '/admin/subscription'
      path: '/subscription'
      fullPath: '/admin/subscription'
      preLoaderRoute: typeof AdminSubscriptionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salary-revision': {
      id: '/admin/salary-revision'
      path: '/salary-revision'
      fullPath: '/admin/salary-revision'
      preLoaderRoute: typeof AdminSalaryRevisionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/renewals': {
      id: '/admin/renewals'
      path: '/renewals'
      fullPath: '/admin/renewals'
      preLoaderRoute: typeof AdminRenewalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org': {
      id: '/admin/org'
      path: '/org'
      fullPath: '/admin/org'
      preLoaderRoute: typeof AdminOrgRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lifecycle': {
      id: '/admin/lifecycle'
      path: '/lifecycle'
      fullPath: '/admin/lifecycle'
      preLoaderRoute: typeof AdminLifecycleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance-docs': {
      id: '/admin/compliance-docs'
      path: '/compliance-docs'
      fullPath: '/admin/compliance-docs'
      preLoaderRoute: typeof AdminComplianceDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminComplianceDocsRoute: typeof AdminComplianceDocsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLifecycleRoute: typeof AdminLifecycleRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminOrgRoute: typeof AdminOrgRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminRenewalsRoute: typeof AdminRenewalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSalaryRevisionRoute: typeof AdminSalaryRevisionRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionRoute: typeof AdminSubscriptionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminComplianceDocsRoute: AdminComplianceDocsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLifecycleRoute: AdminLifecycleRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminOrgRoute: AdminOrgRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminRenewalsRoute: AdminRenewalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSalaryRevisionRoute: AdminSalaryRevisionRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionRoute: AdminSubscriptionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SuperAdminRoute: SuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
